language: php
php:
- 7.2
- 7.3
- nightly
matrix:
  allow_failures:
  - php: nightly
  - php: 7.3
env:
  global:
    secure: YxtZv6TMrjXpMFN/rdzXHW4wTztklHDZ7XQHwtSBx4F+sX2yJG7jIfeOxXIOQw5xqAiu5NX4mUkBY2AezGiMMGtbipGN/h8YQqAmlfyR9cZUTcZNBmDINKJRz6OGRPCHp1L/wevmqirzVnZljioGXy6sX3CDJ+rz2Cotkjq3636/ISPTP4IgtXvtWSPoyX++WT6bd7J2NIGA0Ywa+9N+/Rwk7LNQV5dLpPNZR1eRpwOTZ2A8434+QmYKTdRlWxYoADSQi5OsGuEdWuuhtncNJSIFw2U0OPTtYlMUg/R7Gj0tpknuOqNrv8WrEfkQeXl/sUvUb1x5GOpiC3seUlM3TPn1TaRa7BLA7sLdhZagZIZnvmP1cV5nFHh/1bMF4JivvOqdeomgQW+mdpS1r8MBdbrWCTUXOsfNM88c/pG6Wp4SYD5VT0Utw981387HGX4icwpzbSBrBm2oTL9mgQlRFpzspRpYWVbLwh2IFs/6Q+huMILetjLORWbC+pMVNaPJVUlG/qS6lNY0rLiR4/rfUz+zLYF1TOPzS+GUVmVq80uL3ThGyM0DfQL2CgGBsHv/WsHqFKLHzwvL4UUuVG7mTbnlnxX/xAj5EWMNEEFiXTDwqNngaIW4r1EsO/YyyTYqeprW/3wdzm/uR90BZ8LzD48JFCYp9qmbCrKwgzQinVk=
dist: xenial
os: linux
cache:
  yarn: true
  directories:
  - node_modules
  - vendor
  - "$HOME/pecl_cache"
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: GIS8bQ83gHuPO7dwcy4h3UJLYeRckI+eEBH/xkcrOEkPbxU15DWpAuBBXqyeW+bFHsE+ujVYZiA14HPtS6uQjsha2kz7fLmJYvAFPbA6NaEdF/C73UPlhKKVPnQfhv1FHJuU6FyXmuubTdvx6im3HglFQV7Ps2JcY+ZzBVnoWauysMrKh3tqSwy9I3/WmBl/7kA80I2q9SnzUUpEsCoXCgOEU3ahTuZr3Ta9k5Ap8S2fqAmte+ifFPr7l84af1E3o7kVPP61DRoHy+jj51KR8bLXX3aO0jwush1edScPK4KgvFCpY/Lk6H6F5MHV3Tz0yuuZYuD8iIL1yX7LynW8X8d17EDtohWpM8pBcMOCGJvyq/hnaVHSlpdKpyXdwD/srlmTonbtkDes07987pKrWFrtVi5QZPF1QllBrAO8soUYq0M5lhhqOSkQBYw2idSVUYDksDJibYiBpqPP1qHz52VN4JGSUSBQ4exkx7KR/TwrSO4nZkyM8llW/pyBLQ5fJROL63Q4DqJkz4by1rWtTjNzsTJmpU5dBffvDIV1l9bD8D6rowmtAA/uDK909v9KUOvy1vsyU/loWXvoLM9P3vUyvvKSKcjpxKpIoKJAdzC42CXkLCShw+Ic5e7yysdn1wn+gf85/XQawXSuUZKgLr6L8oeMGGUleCvwXeRCGGE=
    on_success: change
    on_failure: always
services:
- redis-server
- postgresql
install:
- psql -c 'create database travis_ci_test;' -U postgres
- cp .env.travis .env
- composer self-update
- composer install --no-interaction
- php artisan key:generate
- php artisan migrate
- node -v
- yarn install
- yarn run prod
script:
- vendor/bin/phpunit
- if [ -f storage/logs/laravel.log ]; then cat storage/logs/laravel.log; fi
after_success:
- vendor/bin/infection
- travis/automerge