language: php

php: '7.2'

sudo: required
dist: trusty
os: linux

cache:
  yarn: true
  directories:
  - node_modules
  - vendor
  - $HOME/pecl_cache

notifications:
  email:
    on_success: change
    on_failure: always

services:
  - redis-server
  - mongodb

before_install:
  - travis/ci-pecl-install mongodb

install:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - node -v
  - yarn install
  - yarn run prod

script:
  - vendor/bin/phpunit
  - if [ -f storage/logs/laravel.log ]; then cat storage/logs/laravel.log; fi

after_success:
  - if [ $TRAVIS_BRANCH == 'master' ]; then git clone git@github.com:gwaldvogel/city_matters.git $TRAVIS_BUILD_DIR/temp; fi
  - if [ $TRAVIS_BRANCH == 'master' ]; then cd $TRAVIS_BUILD_DIR/temp; fi
  - if [ $TRAVIS_BRANCH == 'master' ]; then git checkout production; fi
  - if [ $TRAVIS_BRANCH == 'master' ]; then git merge --ff-only "$TRAVIS_COMMIT"; fi
  - if [ $TRAVIS_BRANCH == 'master' ]; then git push origin production; fi