#!/bin/bash -e


export GITHUB_REPO='citymatters/citymatters'
export MERGE_BRANCH='master'
export MERGE_PHP_VERSION='7.2'
export TARGET_BRANCH='production'

export GIT_COMMITTER_EMAIL='travis@citymatters.de'
export GIT_COMMITTER_NAME='Travis CI'

if ! [ "$MERGE_BRANCH" = "$TRAVIS_BRANCH" ]; then
    echo "Current branch ($TRAVIS_BRANCH) will not be automerged."
    exit 0
fi

if ! [ "$MERGE_PHP_VERSION" = "$TRAVIS_PHP_VERSION" ]; then
    echo "Current PHP version ($TRAVIS_PHP_VERSION) will not be automerged."
    exit 0
fi

git clone https://github.com/$GITHUB_REPO $TRAVIS_BUILD_DIR/temp
cd $TRAVIS_BUILD_DIR/temp
git checkout $TARGET_BRANCH
git merge --ff-only "$TRAVIS_COMMIT"
export PUSH_URI="https://$GITHUB_SECRET_TOKEN@github.com/$GITHUB_REPO"
git push "$PUSH_URI" "$TARGET_BRANCH" >/dev/null 2>&1